name: Build Rails Application
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'feature/**'

permissions:
      id-token: write
      contents: read
env:
  CLUSTER: rails-aws-dev
  NAMESPACE: rails-aws-dev

jobs:
  build-and-push-image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::592309593815:role/rails-aws-master-github-oidc
          role-session-name: rails-github-ci
          aws-region: us-east-1
          
      - name: Check AWS Creds
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Test
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          
